version: '3'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 50001:50000
    networks:
      - server

networks:
  server:
    external:
      name: host
