version: '3'

services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 50000:50000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - server
